project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  tests: tests

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
