project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  tests: tests

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - Uniswap/uniswap-v3-core@1.0.0
  - Uniswap/uniswap-v3-periphery@1.3.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@uniswap/v3-core=Uniswap/uniswap-v3-core@1.0.0"
      - "@uniswap/v3-periphery=Uniswap/uniswap-v3-periphery@1.3.0"